# Generated by Django 2.0.1 on 2018-01-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
