# Generated by Django 2.0.1 on 2018-07-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='Anon', max_length=20),
            preserve_default=False,
        ),
    ]
