# Generated by Django 2.0.1 on 2018-07-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
